version: '3'
services:
 web:
   build:
     context: .
     dockerfile: Dockerfile
   #add node port and project runing port
   ports:
     - "8000:80"
     - "8001:4000"
     - "8002:8081"
   volumes:
     - .:/var/www/html
     #- ./.env.example:/var/www/html/S25I05V1995A/.env
   depends_on:
     - db1
     - mongo
     - postgres
     - pgadmin
 #mysql
 db1:
   image: mysql:5.7
   container_name: db1
   restart: unless-stopped
   tty: true
   ports:
     - "3307:3306"
   environment:
     MYSQL_DATABASE: arbon
     MYSQL_ROOT_PASSWORD: Aa213111998
     SERVICE_NAME: mysql
   volumes:
     - ./dbdata:/var/lib/mysql/
     #- ./mysql/my.cnf:/etc/mysql/my.cnf
 #MongoDB Service
 mongo:
   image: mongo:4.4.4
   container_name: mongo
   restart: unless-stopped
   tty: true
   ports:
     - "27018:27017"
   volumes:
     - ./mongodata:/data/db


 #postgre service
 postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 55432:5432/tcp
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: Aa@13111998
    volumes:
      - /var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d

 #pgadmin
 pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always

